sonar.projectKey=openvibes-project_openvibes-agent
sonar.organization=openvibes-project


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=openvibes-agent
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
