[package]
name = "ovsvms-rules"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
cel.workspace = true
ovsvms-core = { path = "../ovsvms-core" }
base64.workspace = true
ed25519-dalek.workspace = true
sha2.workspace = true
serde.workspace = true
serde_json.workspace = true
serde-saphyr.workspace = true

[dev-dependencies]
serde-saphyr = { workspace = true, features = ["serialize"] }

[lints]
workspace = true
